[project]
name = "minimal-uv-project-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.5.0",
    "gepa>=0.0.25",
    # "litellm>=1.81.1",  # Seeing AttributeError: 'InternalServerError' object has no attribute 'choices' in gepa/adapters/default_adapter/default_adapter.py
    "gitpython>=3.1.46",
    "litellm==1.80.16",
    "loguru>=0.7.3",
    "mlflow>=3.8.1",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
    "stickler-eval>=0.1.4",
    "typer>=0.21.1",
]

[dependency-groups]
dev = [
    "pre-commit>=4.0.1",
    "pyright>=1.1.408",
    "pytest>=9.0.2",
    "ruff>=0.14.13",
]

[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint]
select = [
    "E", # pycodestyle errors
    "F", # pyflakes
    "I", # import sorting (isort-compatible)
]

[tool.pyright]
pythonVersion = "3.13"
venvPath = "."
venv = ".venv"
include = ["src", "tests"]
exclude = ["**/__pycache__"]
extraPaths = ["src"]
typeCheckingMode = "basic"   # ["off", "basic", "standard", "strict"]
